language: python

env:
  global:
    - TWINE_USERNAME=__token__
    - TWINE_PASSWORD="pypi-AgEIcHlwaS5vcmcCJDVmYjQ3MWVhLTJlYzUtNGQ0Ni1iNDNlLTA4ZDM5OGI5NzM5ZAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgRZ51c6JWwr8L8fKEp03VmrbEFFpqPZDUxg8govB6b4Y"  

notifications:
  email: false

python:
  - 3.8

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #       PRE_CMD=linux32
    #       PLAT=manylinux1_i686
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    #       PLAT=manylinux2010_x86_64

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/docker/build-wheels.sh
  - ls wheelhouse/

after_success:
  - if [[ $TRAVIS_TAG ]]; then python -m pip install twine; python -m twine upload --skip-existing wheelhouse/bpf4*.whl; fi