site_name: bpf4
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex
  - admonition
  - def_list
  - tables

use_directory_urls: false

repo_url: https://github.com/gesellkammer/bpf4

nav:
    - index.md
    - api.md
    - core.md
    - util.md

