name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Install cibuildwheel
        run: python -m pip install -U cibuildwheel twine virtualenv packaging

      - name: Build wheels
        env: 
            CIBW_BUILD: 'cp310-* cp311-* cp312-* cp313-*'
            CIBW_SKIP: 'pp* *686* *-musllinux_*'
            CIBW_ARCHS_MACOS: 'x86_64 arm64'
            CIBW_BUILD_VERBOSITY: 1

        run: |
            python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          overwrite: true
      - name: Upload wheels
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            twine upload --skip-existing wheelhouse/*.whl

        continue-on-error: true
