name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel twine virtualenv

      - name: Build wheels
        env: 
            CIBW_SKIP: pp* *686*
        run: |
            python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
      - name: Upload wheels
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            echo $TWINE_USERNAME
            echo $TWINE_PASSWORD
            twine upload --skip-existing wheelhouse/*.whl
        continue-on-error: true
